### ISSUE TITLE
unable to navigate to URL with all 'D#' notes and 'F#' notes (due to the # symbol)

### ISSUE THREAD

**Issue by erichlof** [darosh/samples-piano-mp3#1]
Hello!  First, thank you for this very helpful resource!  I encountered an issue when trying to view/use/download any notes that are sharped - i.e. all D# and F# pitches.  This is apparently due to the fact that if a # hashtag symbol is used in the url, it instructs browsers to do something not intentional to your file system.  

After researching a bit (I am still learning about all the intricacies of web/html programming), I was finally able to navigate to the file and view it (listen to the .mp3) in my browser by replacing the hashtag symbol with the following characters: %23  (that's percent 2 3). This is apparently a character escape sequence and the url is correctly navigated to.  So for instance, here is the original [non-working link](https://unpkg.com/@audio-samples/piano-mp3-velocity6@1.0.3/audio/D#4v6.mp3) and here is the corrected [working link](https://unpkg.com/@audio-samples/piano-mp3-velocity6@1.0.3/audio/D%234v6.mp3)

I don't know how much of a pain it would be to update all of your D# and F# notes via your package system.  What the authors of Tone.js did to get around this browser url quirk is to simply rename the D#4 and F#4 for instance to Ds4 and Fs4 so there is no issue at all.  Although I did at first think it was Ds as in multiple plural D's, ha ha.  I don't know, maybe Dsharp4 would be less ambiguous but slightly more verbose.

Thanks again for this valuable resource!
-Erich

**Comment by darosh** [comment]
Hi @erichlof 

The original sample files are named with #.

There is 
![image](https://user-images.githubusercontent.com/297320/77100544-17d6cf80-6a16-11ea-8bee-f2874b335ed3.png) 
for that.

I guess the file name and its URI are both valid. 
Maybe just a notice about URI encoding in a readme could the job? (Instead of renaming files and explaining Ds is/are D# :-)

**Comment by erichlof** [comment]
@darosh 
Oh cool - I wasn't aware of the encodeURICompenent.  Yes I agree, a notice about this in a readme would do the trick!
I'll go ahead and close out this issue.  Thanks again!

**Comment by darosh** [comment]
@erichlof  Note added to every readme. Thank you!
